// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDwUY9ZU7KrgQSzREW8Dl8QyombvcIqc',
    appId: '1:356056697601:web:024791532d79254cc42900',
    messagingSenderId: '356056697601',
    projectId: 'shapeos-smarthome',
    authDomain: 'shapeos-smarthome.firebaseapp.com',
    databaseURL: 'https://shapeos-smarthome-default-rtdb.firebaseio.com',
    storageBucket: 'shapeos-smarthome.firebasestorage.app',
    measurementId: 'G-BXG9VJCNKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Vz5fB1qgOZTezJeZO2MXR0ZItoneV-s',
    appId: '1:356056697601:android:78743814d13b3714c42900',
    messagingSenderId: '356056697601',
    projectId: 'shapeos-smarthome',
    databaseURL: 'https://shapeos-smarthome-default-rtdb.firebaseio.com',
    storageBucket: 'shapeos-smarthome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDycKDS80mgPzqHMTNWA5DsqDAw_gZ3r8',
    appId: '1:356056697601:ios:5175d5e074487b59c42900',
    messagingSenderId: '356056697601',
    projectId: 'shapeos-smarthome',
    databaseURL: 'https://shapeos-smarthome-default-rtdb.firebaseio.com',
    storageBucket: 'shapeos-smarthome.firebasestorage.app',
    androidClientId: '356056697601-2b2idamr3f3a04b3tr9muoauhc3vbpf0.apps.googleusercontent.com',
    iosClientId: '356056697601-c4bdneic25i707qt6i7r1e6pfnj9u58n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDycKDS80mgPzqHMTNWA5DsqDAw_gZ3r8',
    appId: '1:356056697601:ios:5175d5e074487b59c42900',
    messagingSenderId: '356056697601',
    projectId: 'shapeos-smarthome',
    databaseURL: 'https://shapeos-smarthome-default-rtdb.firebaseio.com',
    storageBucket: 'shapeos-smarthome.firebasestorage.app',
    androidClientId: '356056697601-2b2idamr3f3a04b3tr9muoauhc3vbpf0.apps.googleusercontent.com',
    iosClientId: '356056697601-c4bdneic25i707qt6i7r1e6pfnj9u58n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhDwUY9ZU7KrgQSzREW8Dl8QyombvcIqc',
    appId: '1:356056697601:web:e341b870d1384077c42900',
    messagingSenderId: '356056697601',
    projectId: 'shapeos-smarthome',
    authDomain: 'shapeos-smarthome.firebaseapp.com',
    databaseURL: 'https://shapeos-smarthome-default-rtdb.firebaseio.com',
    storageBucket: 'shapeos-smarthome.firebasestorage.app',
    measurementId: 'G-NG6QKED27T',
  );

}